language: python
addons:
  firefox: "latest-esr"
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

env:
  global:
    - MOZ_HEADLESS=1
  matrix:
    - DJANGO="1.9"
    - DJANGO="1.10"
    - DJANGO="1.11"
    - DJANGO="2.0"
    - DJANGO="2.1"
    - DJANGO="2.2"
    - DJANGO="3.0"
    - DJANGO="3.1"

before_install:
  - ./get_gecko.sh
  - export PATH=$PATH:$PWD/geckodriver
  - export MOZ_HEADLESS=1
  - echo "Path is" $PATH

install: pip install tox-travis coveralls
script: tox
after_script: cat geckodriver.log
after_success:
  coveralls
